id: P351510C5
initial_creation_type: ocr
source_metadata:
  volumes:
    28574899163240e1bb16e54ae11f447a:
      base_file: v017.txt
      image_group_id: I1PD95862
      title: སྒྲོན་མ་གསལ་བ་ཞེས་བྱ་བའི་འགྲེལ་བཤད།
      total_pages: 1158
      volume_number: 17
